### ISSUE TITLE
Should allude to the other variables that could be set.

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#10]
I used the network variable to change from 10.4 to 10.30.

There other variables that can be set as well.  Look in the aws.tf to see the others variable that could be changed such as  network prefix and  aws region.   FYI - You will need a region that has at least three availability zones if you want full ha.  see xxx for the reason why.

**Comment by jhunt** [comment]
These are "documented" to an extent inside the aws.tf file.
