### ISSUE TITLE
Client can not connect to OpenVPN

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#100]
i have setup OpenVPN following the codex guide but I get the following error when try to connect. Could you please advice?

> Mar 29 11:58:50: ---------
> Mar 29 11:58:50: Checking reachability status of connection...
> Mar 29 11:58:50: Connection is reachable. Starting connection attempt.
> Mar 29 11:58:51: OpenVPN 2.3.14 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Jan 14 2017
> Mar 29 11:58:51: library versions: OpenSSL 1.0.2j  26 Sep 2016, LZO 2.09
> Mar 29 11:58:52: WARNING: No server certificate verification method has been enabled.  See > http://openvpn.net/howto.html#mitm for more info.
> Mar 29 11:58:52: Attempting to establish TCP connection with [AF_INET]52.10.101.137:443 [nonblock]
> Mar 29 11:58:55: TCP connection established with [AF_INET]52.10.101.137:443
> Mar 29 11:58:55: TCPv4_CLIENT link local: [undef]
> Mar 29 11:58:55: TCPv4_CLIENT link remote: [AF_INET]52.10.101.137:443
> Mar 29 11:58:55: WARNING: Bad encapsulated packet length from peer (18516), which must be > 0 and <= 1547 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
> Mar 29 11:58:55: Connection reset, restarting 

Examining the openvpn_z1 instance i could see the openvpn.conf is
> mode server
> writepid /var/vcap/sys/run/openvpn/openvpn.pid
> client-config-dir /var/vcap/jobs/openvpn/etc/ccd
> ca /var/vcap/jobs/openvpn/etc/ca.crt
> cert /var/vcap/jobs/openvpn/etc/server.crt
> key /var/vcap/jobs/openvpn/etc/server.key
> dh /var/vcap/jobs/openvpn/etc/dh.pem
> crl-verify /var/vcap/jobs/openvpn/etc/crl.pem
> proto tcp
> port 443
> comp-lzo
> group nogroup
> user nobody
> status /var/vcap/sys/log/openvpn/status.log
> dev tun0
> local 0.0.0.0
> server 172.31.255.0 255.255.255.0
> 
> push "route 10.10.0.0 255.255.0.0"
> 
> 
> push "persist-tun"
> push "ping 15"
> push "ping-restart 60"
> keepalive 15 60
> topology subnet
> persist-key
> persist-tun

_P.S Attempted to copy relevant conf in the client side, and set MTU  to default (i.e. 1500) but with no success_

**Comment by ipolyzos** [comment]
I have exposed one node through elastic ip bypassing the elb and works fine !
It seems that I have made a mistake in the ELB setup...

**Comment by 7hunderbird** [comment]
Double checked with @ipolyzos.  We're alright to close this ticket.
