### ISSUE TITLE
Why certstrap rather than safe?

### ISSUE THREAD

**Issue by drnic** [starkandwayne/codex#109]
Codex documentation uses https://github.com/square/certstrap to generate certificates. Why certstrap rather than similar features in `safe` CLI that's used elsewhere in codex/genesis?

Is this what I'm supposed to use to get https://github.com/genesis-community/concourse-genesis-kit/issues/2 to work?

**Comment by drnic** [comment]
Pending answer, I've added `certstrap` to our APT repo:

```
echo "deb [trusted=yes] https://apt.starkandwayne.com stable main" > /etc/apt/sources.list.d/starkandwayne.list
apt-get update
apt-get install certstrap
```

**Comment by geofffranks** [comment]
The docs indicating certstrap are very old. The genesis v2 CF kit uses safe rather than certstrap.

**Comment by 7hunderbird** [comment]
We will use safe as we update the docs to use genesis v2 kits.
