### ISSUE TITLE
should state the os your bastion machine is running on

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#11]
login to your aws account 
access the ec2 services
click on instances
find the instance with the name bastion and click on it

The information displayed below and saw the AMI ID being ubuntu

I then clicked on the connect button and saw it provided the help information.

The connect button should now be available with the information you need to access the bastion machine.

**Comment by jhunt** [comment]
I'm confused; why do you need to know the bastion host OS?

**Comment by norman-abramovitz** [comment]
because I did not know the username would be ubuntu instead of centos like I have been using so far.  By knowing the OS I would known centos username would not be correct.

**Comment by jhunt** [comment]
Ah.  Fair enough.

Any thoughts on creating a bastion AMI that we could use?
