### ISSUE TITLE
Azure terraform template contain duplicate output

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#115]
In an attempt to initialize the Azure terraform template I get an error due to duplicate outputs, i.e.

> $ terraform init
> Error getting plugins: module root: 4 error(s) occurred:
> 
> * azure.network.staging-cf-core-0.subnet: duplicate output. output names must be unique.
> * azure.network.staging-cf-runtime-0.subnet: duplicate output. output names must be unique.
> * azure.network.staging-cf-runtime-1.subnet: duplicate output. output names must be unique.
> * azure.network.staging-cf-runtime-2.subnet: duplicate output. output names must be unique.

**Comment by 7hunderbird** [comment]
Closed by https://github.com/starkandwayne/codex/pull/116
