### ISSUE TITLE
Azure Storage Accounts  exist

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#117]
The Azure terraform deployment fails due to storage accounts already exist i.e. "The storage account named ** *** ** is already taken."

> Error applying plan:
> 
> 3 error(s) occurred:
> 
> * azurerm_storage_account.bastion: 1 error(s) occurred:
> 
> * azurerm_storage_account.bastion: Error creating Azure Storage Account 'bastionaccount': storage.AccountsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="StorageAccountAlreadyTaken" Message="The storage account named bastionaccount is already taken."
> * azurerm_storage_account.nat: 1 error(s) occurred:
> 
> * azurerm_storage_account.nat: Error creating Azure Storage Account 'nataccount': storage.AccountsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="StorageAccountAlreadyTaken" Message="The storage account named nataccount is already taken."
> * azurerm_virtual_network.default: 1 error(s) occurred:
> 
> * azurerm_virtual_network.default: network.VirtualNetworksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet AZR-C01-IN-TITAN-008-dmz is in use by /subscriptions/a44d6b67-2946-4772-bf8d-e3ba1665123e/resourceGroups/AZR-C01-IN-TITAN-008/providers/Microsoft.Network/networkInterfaces/bastionNetworkInterface/ipConfigurations/bastion_ip and cannot be deleted." Details=[]
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> make: *** [deploy] Error 1

**Comment by ipolyzos** [comment]
Considering that Azure Storage is global and also accessible through DNS the default 'bastionaccount' and 'nataccount' names it would be a good idea to be prefixed with a user-defined string.

**References:** 
- [Azure Storage Documentation](https://docs.microsoft.com/en-us/azure/storage/)
- [Azure Storage Naming Rules](https://blogs.msdn.microsoft.com/jmstall/2014/06/12/azure-storage-naming-rules/)
- [Azure Naming Conventions](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)

**Comment by 7hunderbird** [comment]
Closed by https://github.com/starkandwayne/codex/pull/116
