### ISSUE TITLE
[Proposal] Use of Managed disks in Azure infrastructure

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#124]
I would like to propose the use Azure managed disks for Azure NAT and Bastion VM resources in an attempt to increase availability, scalability and fault tolerance. The announcement of managed disks along with some more resources can be found on the links below:

- [Announcing general availability of Managed Disks and larger Scale Sets](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-gb%2Fblog%2Fannouncing-general-availability-of-managed-disks-and-larger-scale-sets%2F&data=02%7C01%7CSenthuran.Sivananthan%40microsoft.com%7C6805889f7d84418036c108d501bfef85%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636416846257519526&sdata=yCBv5EThrptt4LDr3UFixkhLOPCzOzNr3o8in8p3P14%3D&reserved=0)
- [Azure - Managed Disks Presentation](https://github.com/SenthuranSivananthan/azure/tree/master/ManagedDisks)
- [Azure Managed Disks Overview](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/managed-disks-overview)
- [Managed Disks - Persistent, secured disk storage for Azure Virtual Machines](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-gb%2Fservices%2Fmanaged-disks%2F&data=02%7C01%7CSenthuran.Sivananthan%40microsoft.com%7C6805889f7d84418036c108d501bfef85%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636416846257519526&sdata=ONybBYy3xPbPsNNUpf3PQ5NHVpl9wlXHZ9qp7vDiJMw%3D&reserved=0)
- [Scalability targets for virtual machine disks](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-gb%2Fazure%2Fstorage%2Fcommon%2Fstorage-scalability-targets%23scalability-targets-for-virtual-machine-disks&data=02%7C01%7CSenthuran.Sivananthan%40microsoft.com%7C6805889f7d84418036c108d501bfef85%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636416846257519526&sdata=BPXIsd49Vd0Sen%2FFJcJ3Zy%2BvA4l%2FHmutE7bZAEcZUGA%3D&reserved=0)
- [Migrate Azure VMs to Managed Disks in Azure](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-gb%2Fazure%2Fvirtual-machines%2Fwindows%2Fmigrate-to-managed-disks&data=02%7C01%7CSenthuran.Sivananthan%40microsoft.com%7C6805889f7d84418036c108d501bfef85%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636416846257519526&sdata=tp93BNIEvnjYhg3nywein1VjaxlD3rneX%2BkrNh0bHA8%3D&reserved=0)
- [Terraform - azurerm_managed_disk](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.terraform.io%2Fdocs%2Fproviders%2Fazurerm%2Fd%2Fmanaged_disk.html&data=02%7C01%7CSenthuran.Sivananthan%40microsoft.com%7C6805889f7d84418036c108d501bfef85%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636416846257519526&sdata=BqdncQhtvCKAXlvdgGh8jvWcwTXAaHHndNj%2BPnoNQCw%3D&reserved=0)

**Comment by 7hunderbird** [comment]
This is really great research that you've done @ipolyzos.  Thanks so much!
