### ISSUE TITLE
Is the vault download incorrect?

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#14]
Vault is at version 0.6.0   We installed version 0.5.0.

https://www.vaultproject.io/downloads.html

https://releases.hashicorp.com/vault/0.6.0/vault_0.6.0_linux_amd64.zip

**Comment by jhunt** [comment]
We don't actually use the vault CLI for more than just `vault init`, so it's not a huge deal.  If you want, put in a PR against the jumpbox script repo to fix that.
