### ISSUE TITLE
Should binary rubies already exist?

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#15]
Not sure this is an issue or not, but it caught my eye when doing the jumpbox user command.

Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/16.04/x86_64/ruby-2.2.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

**Comment by jhunt** [comment]
I don't think so, is this causing you issues in setting up the bastion host?

**Comment by norman-abramovitz** [comment]
No problems so far.  Just saw the message and made me wonder if something was missing.
