### ISSUE TITLE
should Go be installed when doing either jumpbox system or jumpbox user?

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#16]
I ran into the previous incarnation of the codex where I needed to build some app with go.  Not sure if the issue still exists not.

**Comment by jhunt** [comment]
Tools should not require compilation on-box.  If we are building tools, we need to be creating release pipelines to drop pre-compiled (version-controlled) binaries on Github.  If someone else is being bad, we need to help them be better.
