### ISSUE TITLE
proto bosh documentation for vault path for access_key and secret_key are inconsistent

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#20]
The documentation for proto bosh states to use the following command to add the keys.

safe set secret/aws access_key secret_key

The reference in the yml snippet  is defined as follows: 

meta:
    access_key: (( vault "secret/**proto/**aws:access_key" ))
    secret_key: (( vault "secret/**proto**/aws:secret_key" ))

no error is generated when I did a make manifest.   The error only showed up on the make deploy

**Comment by jhunt** [comment]
I actually just fixed this on HEAD
