### ISSUE TITLE
failure on vault deployment

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#22]
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 3
  Started preparing deployment > Preparing deployment. Failed: Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3232.8' doesn't exist (00:00:00)

Error 50003: Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3232.8' doesn't exist

Task 3 error

For a more detailed error report, run: bosh task 3 --debug

**Comment by norman-abramovitz** [comment]
Given that latest stemcell is 3262.2, how often does the genesis index get updated?

**Comment by geofffranks** [comment]
Duplicate of #21?

**Comment by norman-abramovitz** [comment]
Closing issue since this is a duplicate and will write a new issue about the genesis index updating process.
