### ISSUE TITLE
Vault deployment not setup for https access

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#24]
Will need to figure out what is needed to have vault releases support either https or http.

I switched over to http to figure out ha setup instructions.

norm@ip-10-30-0-102:~$ safe target proda
Now targeting proda at https://10.30.1.16:8200
norm@ip-10-30-0-102:~$ safe vault init
Error initializing Vault: Put https://10.30.1.16:8200/v1/sys/init: tls: oversized record received with length 20527

This error usually means that the server is running with TLS disabled
but the client is configured to use TLS. Please either enable TLS
on the server or run the client with -address set to an address
that uses the http protocol:

    vault <command> -address http://<address>

You can also set the VAULT_ADDR environment variable:

    VAULT_ADDR=http://<address> vault <command>

where <address> is replaced by the actual address to the server.
!! exit status 1

**Comment by jhunt** [comment]
I added an env_hook called `cert` that generates a self-signed cert via OpenSSL, can you give that a shot?

**Comment by norman-abramovitz** [comment]
tried it but not yet.

This is the startup info from bosh vm before the vault init.  It should on https:// instead of http:   

I need to check out the vault release to see if I can set anything to change the behavior.  If I remember correctly, there is a vault config parameter that needs to be set. 

## vault z1 log after the bosh deploy
 vault.log
==> Vault server configuration:

         Log Level: info
             Mlock: supported: true, enabled: true
           Backend: consul (HA available)
 Advertise Address: **http://10.30.1.16:8200**
        Listener 1: tcp (addr: "0.0.0.0:8200", **tls: "disabled"**)
           Version: Vault v0.5.2

==> Vault server started! Log data will stream in below:

bosh_ouvmewl44@9fe2c70b-874e-4d82-b980-ca271f34b215:/var/vcap/sys/log/vault$ ls -l
total 4
-rw-r--r-- 1 root root 350 Jul  1 03:36 vault.log---

## The server.hcl file 

 cat server.hcl
backend "consul"{
  path = "vault/"
}
listener "tcp" {
 address = "0.0.0.0:8200"
 _**tls_disable = 1**_
 tls_cert_file = "/var/vcap/jobs/vault/ssl/certificate.pem"
 tls_key_file  = "/var/vcap/jobs/vault/ssl/key.pem"
}

# pem files (only contains a new line)
bosh_ouvmewl44@9fe2c70b-874e-4d82-b980-ca271f34b215:/var/vcap/jobs/vault/ssl$ ls -la
total 16
drwxr-xr-x 2 root root 4096 Jul  1 03:33 .
drwxr-xr-x 8 root root 4096 Jul  1 03:36 ..
-rw-r--r-- 1 root root    1 Jul  1 03:33 certificate.pem
-rw-r--r-- 1 root root    1 Jul  1 03:33 key.pem

**Comment by norman-abramovitz** [comment]
Found this in https://github.com/cloudfoundry-community/vault-boshrelease/blob/master/jobs/vault/templates/config/vault.conf.erb

<%
  tls = false
  schema = "http"
  **if_p("vault.listener.tcp.tls.certificate", "") do |cert|
    if_p("vault.listener.tcp.tls.key", "") do |key|
      if cert != "" and key != ""
        tls = true
        schema = "https"
      end
    end**
  end
%>

I am on the correct path given this code segment.  Maybe I can use the new spruce ((file command) since the data should be in the .tls subdirectory.  Time to sleep now.

**Comment by norman-abramovitz** [comment]
your env hook is not writing to the proto vault yet

        **#** safe write "${VAULT_PREFIX}/tls" "certificate@${where}/vault.pem" "key@${where}/vault.key"
        tail -n100 ${where}/vault.key ${where}/vault.pem
        rm -fr ${where}

**Comment by norman-abramovitz** [comment]
up and adam

The where variable is set to 
where=${DEPLOYMENT_ROOT}/${DEPLOYMENT_SITE}/${DEPLOYMENT_ENVIRONMENT}/.tls

The credentials.yml file is created 
cat > ${where}/credentials.yml <<EOF

but before it can be used it gets blown away by rm -rf command

I am assuming you meant to overwrite the site/env/credentials.yml file.

**Comment by jhunt** [comment]
Above issues with env hook badness should be fixed now.

**Comment by norman-abramovitz** [comment]
The manual process was documented in the codex github.   There was some notes about improving safe to be able to do the unseal step.

**Comment by norman-abramovitz** [comment]
added issue to safe so we can close off this issue.
