### ISSUE TITLE
About gitbook.md

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/codex#28]
From the title, it should be knowledge or information about gitbook. The introduction about Codex at the beginning will be better in readme.md instead.

**Comment by xiujiao** [comment]
Will it be a good idea to put how to push and update gitbook here?

**Comment by jhunt** [comment]
Yes.  That should go in the README.md

The README.md is a place to put meta-documentation, that is documentation _about_ the documentation itself.  Explain gitbook, describe the update process, link to the gitbook URL, etc.  It can also detail the aims and goals of the project, how contributing works (as we formalize that procedure), etc.
