### ISSUE TITLE
not all regions have 3 availability zones

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#5]
There seems to assumption that there are 3 availability zones.   This is not true for us-west-1(Northern California).   It has two and the zones are a an c.

**Comment by jhunt** [comment]
Yup.

Per http://aws.amazon.com/about-aws/global-infrastructure/, neither do Beijing, Singapore, Frankfort, GovCloud, or Seoul.  We do not deploy CF to those environments, since Consul won't survive an update / redeploy.

(Although that page does say that N. California has 3 zones, and the existence of a 'c' zone makes me wonder where 'b' went off to...)

**Comment by norman-abramovitz** [comment]
Should we state in the docs only us-west-2, us-east-1, etc should be used?  It is possible, but not disaster recovery safe to to use the same availability zones.

**Comment by jhunt** [comment]
I wouldn't name any regions, but if you want to explain more on why three AZs are necessary, I'm sown

**Comment by norman-abramovitz** [comment]
Cloud Foundry uses Consul by Hashicorp for various purposes, but its
distributed datacenter high availability that needs some extra explanation.
Many high availability software packages allows you to run with a single
node cluster for its degraded mode.   Consul does not.  Consul defines an available cluster by having a quorum of nodes defined by the following formula (nodes/2) + 1 >= 2
If you do not have at least two nodes in your cluster, your cluster does
not have a quorum and your cluster is marked unavailable. 

Even in a two node configuration, you do not have high availability
since one node going down means you do not have a quorum and thus no cluster.
So you need at least three nodes to have high availability.  Consul's degraded mode is a two node cluster.

What does mean for running cloud foundry on Amazon Web Services?
You will want to have three availability zones.
An availability zone is an independent datacenter (power, machines, networking, etc) but also has low latency network to its sister availability zones.
An availability zone corresponds to the Consul cluster node.

If you define the three cloud foundry instances in only two
availability zones, you have some minimal level of high availability
It is not the strongest strongest high availability since losing an availability zone that has the two cloud foundry instances would make Consul lose its quorum.

**Comment by jhunt** [comment]
Can we put that in the repo?

**Comment by norman-abramovitz** [comment]
Of course!  I will ask tbird where though.

**Comment by 7hunderbird** [comment]
@norman-abramovitz Let's put it here to start:

https://github.com/starkandwayne/codex/blob/master/network/aws.md

Thanks, good catch!

**Comment by 7hunderbird** [comment]
This is documented here: https://github.com/starkandwayne/codex/blob/master/aws.md#consul-and-cloud-foundry
