### ISSUE TITLE
AWS: no CNAME creation for <env>-cf-ssh-elb & cf ssh <app-name> not working?

### ISSUE THREAD

**Issue by djvdorp** [starkandwayne/codex#75]
According to the documentation, and myself trying it out, the only CNAME being created will be the one for the `<env>-cf-elb` and not another one for the `<env>-cf-ssh-elb`:

```
From here we need to configure our domain to point to the ELB. Different clients may use different DNS servers. 
No matter which DNS server you are using, you will need add a CNAME record that maps the domain name to the ELB endpoint. 
In this project, we will set up a Route53 as the DNS server. 
You can log into the AWS Console, create a new Hosted Zone for your domain. 
Then go back to the terraform/aws sub-directory of this repository and add to the aws.tfvars file the following configurations:

aws_route53_prod_enabled = "1"
aws_route53_prod_hosted_zone_id = "XXXXXXXXXXX"

As usual, run make manifest to compile your Terraform plan and if everything worked out you, deploy the changes:

$ make deploy
```

Will give you:

```
+ aws_route53_record.prod-cf-cname
    fqdn:               "<computed>"
    name:               "*.prod"
    records.#:          "1"
    records.0000000000: "XXX-prod-cf-elb-000000000.us-east-1.elb.amazonaws.com"
    ttl:                "300"
    type:               "CNAME"
    zone_id:            "XXXXXXXXXXXXXX"

Plan: 1 to add, 0 to change, 0 to destroy.
```

The reason why I found this out, is the fact that out-of-the box it seems that my `cf ssh <app-name>` is not working, and I am trying to pinpoint why this is not working right away (besides the missing CNAME), since the configuration that has been deployed should allow to do so AFAIK?

**Comment by djvdorp** [comment]
One thing that I am not sure about, but might explain why `cf ssh <app-name` is not working, might be the fact that the `access_z*` VMs are in `prod-cf-core-*` Security Groups, while `router_z*` VMs are in `prod-cf-edge-*`. 

According to `tcpdump port 2222` on the `access_z*` VMs there is no traffic incoming on that port at all, resulting in the `<env>-cf-ssh-elb` having Instance Status: `OutOfService` thanks to the `HealthCheck` on `TCP:2222` failing for obvious reasons.

My `cf ssh <app-name>` then ends with this, probably because there is no VM (EC2 Instance) listening behind the `<env>-cf-ssh-elb`:
```
FAILED
Error opening SSH connection: ssh: handshake failed: EOF
```

**Comment by djvdorp** [comment]
See related PR (for the `cf ssh <app-name>` not working-part): https://github.com/starkandwayne/cf-deployment/pull/14

**Comment by djvdorp** [comment]
See related PR (for the `cf ssh <app-name>` not working-part): https://github.com/starkandwayne/codex/pull/77

**Comment by jhunt** [comment]
https://github.com/starkandwayne/cf-deployment/pull/14 has been merged, as has #77

**Comment by djvdorp** [comment]
Thanks a lot for merging @jhunt! These two changes should allow `cf ssh <app-name>` to work again.

Then the only remaining part of this issue would be the question if the Terraform template _should_ create a CNAME record for the `<env>-cf-ssh-elb` when `aws_route53_prod_enabled = 1` and `aws_route53_prod_hosted_zone_id` is set, I do think so, but I didn't send in a PR for this just yet.
If you agree that it should, and thus enabling the `cf ssh` feature to work out-of-the-box, I will try to also send a PR in for this so that this issue can be wrapped up and then closed.

**Comment by djvdorp** [comment]
See related PR (for the `cf-ssh-elb` CNAME not created-part): https://github.com/starkandwayne/codex/pull/78

**Comment by jhunt** [comment]
I love PRs.  Especially ones that make things work better out-of-the-box!

**Comment by djvdorp** [comment]
Thanks for the love @jhunt and also @7hunderbird for merging #78. Closing this one now, as both issues are resolved now. 

The only remaining one open is #79 to have `cf ssh <app-name>` to be 100% functional out-of-the-box, but that is a separate issue (be it related to this one).
