### ISSUE TITLE
AWS: access_z* VMs can not access the Internet (because they have no Public IP while using AWS IGW)

### ISSUE THREAD

**Issue by djvdorp** [starkandwayne/codex#79]
Now that https://github.com/starkandwayne/codex/pull/78 is merged (see https://github.com/starkandwayne/codex/issues/75 for more information), there is one missing piece in the puzzle to get `cf ssh <app-name>` working, and that is to resolve this error:

```
{"timestamp":"1478169322.951416016","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.authenticate-starting","log_level":1,"data":{"session":"5088"}}
{"timestamp":"1478169327.951842785","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.exchange-access-code-for-token.request-failed","log_level":2,"data":{"error":"Post https://uaa.system.my-cf-domain.com/oauth/token: dial tcp 52.207.XX.XX:443: i/o timeout","session":"5088.1"}}
{"timestamp":"1478169327.951933622","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.authenticate-finished","log_level":1,"data":{"session":"5088"}}
{"timestamp":"1478169327.951951265","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"Authentication failed","user":"cf:bacfb6f6-595e-4e2a-9587-XXXXXXXXXXXX/0"}}
```

The reason this error occurs (the `ssh-proxy` on `access_z*` is having trouble authenticating with the `uaa`) is because the `access_z*` VMs are now in the `router*` networks (`prod-cf-edge-*` Subnets, see my earlier change https://github.com/starkandwayne/cf-deployment/pull/14) but the Route Table (`prod-1-external`) is configured to use an [AWS Internet Gateway](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Internet_Gateway.html) to access the Internet, but since the `access_z*` VMs do not have a Public IP address, this is not going to work:

> To enable access to or from the Internet for instances in a VPC subnet, you must do the following:
> 
> - [X] Attach an Internet gateway to your VPC.
> - [X] Ensure that your subnet's route table points to the Internet gateway.
> - [ ] Ensure that instances in your subnet have public IP addresses or Elastic IP addresses.
> - [X] Ensure that your network access control and security group rules allow the relevant traffic to flow to and from your instance.

Also explained [here](https://aws.amazon.com/vpc/faqs/):

> Q. How do instances without public IP addresses access the Internet?
> 
> Instances without public IP addresses can route their traffic through a NAT gateway or a NAT instance to access the Internet. These instances use the public IP address of the NAT gateway or NAT instance to traverse the Internet. The NAT gateway or NAT instance allows outbound communication but doesn’t allow machines on the Internet to initiate a connection to the privately addressed instances.

There are two possible solutions for this problem:
1. change the relevant files in [cf-deployment](https://github.com/starkandwayne/cf-deployment) to auto-assign a Public IP to the VMs in the `access_z*` Resource Pools. 
(This is only supported starting from [v60](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/commit/2af675350751c8a591906854a787c2ea272ca5d3) of the `bosh-aws-cpi`, currently [bosh-deployment](https://github.com/starkandwayne/bosh-deployment) uses [v53](https://github.com/starkandwayne/bosh-deployment/blob/master/global/releases/bosh-aws-cpi/url).)
2. change the relevant files in [codex](https://github.com/starkandwayne/codex) to make it use a NAT instance (does not require a Public IP on the instances) instead of the AWS Internet Gateway.

The impact of this change is not trivial, and I am honestly not 100% sure which one of the solutions is better or more desirable, because I was not involved in setting up [The Network Plan](https://github.com/starkandwayne/codex/blob/master/network.md).

This issue is merely a discussion point, requesting feedback and/or help on how to resolve this matter, to completely fix the `cf ssh <app-name>` functionality in this setup. Also a reference for myself on why this is currently broken, and how this can be fixed. I am looking forward to your input, thanks in advance!

(Besides the above, the `cf-ssh-elb` Security Group should also allow Outbound `TCP traffic over port 80/443 and maybe also 4443`. Or maybe even allow Outbound `All traffic` like the `cf-elb` Security Group does? Yet another discussion point, requesting feedback and/or help for this one too.)

CC @jhunt @7hunderbird @frodenas

**Comment by jhunt** [comment]
When was v60 released, and are there any known pitfalls or gotchas with it?

**Comment by djvdorp** [comment]
I am not that experienced on the matter, but the [bosh-aws-cpi-release release notes](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases) between v53...v60 seem to not point out any particular pitfalls or gotchas.

And maybe useful input to add to the conversation, I spoke with some people on the OSS CloudFoundry Slack (diego channel) and **jvshahid** commented:
> @djvdorp we usually don't use public ips on aws. instead we use a NAT instance (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html) and set the routes of the subnets to use it.

**Comment by djvdorp** [comment]
And maybe useful input to add to the conversation, I spoke with some people on the OSS CloudFoundry Slack (diego channel) and **jvshahid** commented:
> @djvdorp we usually don't use public ips on aws. instead we use a NAT instance (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html) and set the routes of the subnets to use it.

Also, another tool with a similar goal to the Terraform-part of this codex (bootstrap an environment), [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader), resolves outgoing internet access in the following way:

```
AWS Internet Gateway (IGW):
- used for BOSH subnet (bosh director) with a Public IP
- used for LoadBalancer{1,2,3} subnets (load balancers) with Public IPs

NAT instance (EC2 box):
- used for Internal{1,2,3} subnets (CF deployments) without Public IPs
- used for Diego{1,2,3} subnets (Diego deployments) without Public IPs
```

**Comment by djvdorp** [comment]
See also: [AWS Documentation > Scenario 2: VPC with Public and Private Subnets (NAT)](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html)

**Comment by djvdorp** [comment]
I propose that the smallest (sane) change possible would consist of this, without resorting to adding Public IPs to the `access_z*` VMs:

1. Create a new (third) Route Table besides the existing `<vpc_name>-external` and `<vpc_name>-internal` Route Tables, call it something like `<vpc_name>-external-nat`.
2. Make this new (third) Route Table identical to the `<vpc_name>-external`, except for the fact that it uses a NAT instance (EC2 box) for Destination `0.0.0.0/0` instead of an AWS Internet Gateway (IGW).
3. Change the Subnet Associations to move all the `<vpc_name>-ENV-cf-edge-{0,1,2}` to the new (third) Route Table.

Besides the above, the `cf-ssh-elb` Security Group should also allow Outbound `TCP traffic over port 80/443 and maybe also 4443`. Or maybe even allow Outbound `All traffic` like the `cf-elb` Security Group does? Yet another discussion point, requesting feedback and/or help for this one too.

**Comment by djvdorp** [comment]
Maybe I am mistaken, but could this already be resolved now by this PR (https://github.com/starkandwayne/cf-deployment/pull/19) and this commit when it got merged (https://github.com/starkandwayne/cf-deployment/commit/520a745b57da0621beb471ef4450867ffdb5f6ab) ?
