### ISSUE TITLE
Copy the terraform directory to keep the codex in intact

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#8]
I believe we should not be modifying the codex files directly since we might want to come back and standup a new datacenter.   We could mention that copy and paste works but the codex files should stay pristine.   It is most likely being cloned so it also helps avoid a mistake of checking in code.

**Comment by jhunt** [comment]
That's a fairly junior mistake, given that you have to add, commit and _then_ push to the remote repo.
