### ISSUE TITLE
Error Deploying proto-BOSH with Shield Agent Job

### ISSUE THREAD

**Issue by djvdorp** [starkandwayne/codex#82]
I am aware of [this identical entry in troubleshooting.md](https://github.com/starkandwayne/codex/blob/master/troubleshooting.md#proto-bosh--shield), which says:

>If you see the error below, then you are running the scripts and everything from the bastion user, you MUST use the jumpbox scripts/users/Vault in order for it to be nice and not throw errors at you.

However, to my knowledge, I am already running `vault server -dev` (in screen/tmux) as user `juser` and thus I have no idea what I am doing wrong here? I am pretty sure I did the exact same thing (also as `juser`, the user created via `jumpbox useradd`) on another deployment with the same version of Genesis (v1.5.5) and it worked just fine.

```
Command 'deploy' failed:
  Deploying:
    Building state for instance 'bosh/0':
      Rendering job templates for instance 'bosh/0':
        Rendering templates for job 'shield-agent/1554599af5a2c1615b31de9312990fa4f7dfbcbe':
          Rendering template src: config/target.json.erb, dst: config/target.json:
            Rendering template src: /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/bosh-init-release923537472/extracted_jobs/shield-agent/templates/config/target.json.erb, dst: /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/rendered-jobs872490852/config/target.json:
              Running ruby to render templates:
                Running command: 'ruby /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/erb-renderer411035082/erb-render.rb /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/erb-renderer411035082/erb-context.json /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/bosh-init-release923537472/extracted_jobs/shield-agent/templates/config/target.json.erb /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/rendered-jobs872490852/config/target.json', stdout: '', stderr: '/home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/erb-renderer411035082/erb-render.rb:180:in `rescue in render': Error filling in template '/home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/bosh-init-release923537472/extracted_jobs/shield-agent/templates/config/target.json.erb' for shield-agent/0 (line 2: #<TypeError: nil is not a symbol nor a string>) (RuntimeError)
        from /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/erb-renderer411035082/erb-render.rb:166:in `render'
        from /home/juser/.bosh_init/installations/42cd9c42-5f4c-40fc-6258-5e3cf721ab98/tmp/erb-renderer411035082/erb-render.rb:191:in `<main>'
':
                  exit status 1
Makefile:25: recipe for target 'deploy' failed
make: *** [deploy] Error 1
```

CC @dstarner15 @jhunt @7hunderbird

**Comment by jhunt** [comment]
Yeah, this error is because `bosh-init` doesn't resolve IP addresses like regular BOSH does.  You probably want to try upgrading SHIELD from 6.3.5 to 6.4.0, but I don't know if Codex has been vetted against 6.4.0.

Specifically, you want to set the `shield.agent.ip` property that the 6.4.0 release notes describe:

> New shield.agent.ip property, for when you just can't rely on
> IP address auto-detection (i.e. when deploying via bosh-init),
> and you still want to auto-provision stuff.

HTH

**Comment by djvdorp** [comment]
Hi @jhunt -- thanks a lot for your help and input, is is appreciated a lot (and especially considering it is pretty much an non-working day today). 

The SHIELD (`shield-boshrelease`) version that seems to be released the bosh-deployment is v6.3.0 -- so even older than the v6.3.5 you referred to. 

At this point, I am not yet setting up and using SHIELD, so what (placeholder) value would be acceptable for the `shield.agent.ip` so that I could proceed, if there is no SHIELD yet (and might not even be there soon)? 
I kinda assume that `nil` is not going to be an acceptable value there.

I might sound a little bit repetitive, but that is because I am kinda pulling my hairs out trying to figure out how it is possible that the exact same version of `genesis` and `bosh-deployment` to deploy a proto-BOSH in `us-east-1` worked right away, while it fails when redoing this in `eu-central-1`, also via the exact same steps in the beautiful manual (`codex`)?

**Comment by jhunt** [comment]
I don't understand the discrepancy either, all things being equal.

If you aren't planning on using SHIELD, or at least aren't using it in the near future, you can remove the release from the deployment repo by manually editing the `<site>/site/releases` file.  Above and beyond that, you may also manually remove the `global/releases/shield` directory if you don't want SHIELD anywhere else.

I'll get a patch out to both codex and the BOSH deployment template this week.

**Comment by djvdorp** [comment]
Thanks @jhunt for the reply and workaround, looking forward to the patches as well. Much appreciated!

**Comment by jhunt** [comment]
I updated the template deployments.  Turns out there is no need to update the actual codex docs.
