### ISSUE TITLE
We should specify the groups/permissions the IAM user needs.

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/codex#9]
poweruser
maybe admin if allowed

**Comment by norman-abramovitz** [comment]
poweruseraccess
administratoraccess
amazonfulls3access

**Comment by norman-abramovitz** [comment]
Error message when you do set the permissions

Error applying plan:

1 error(s) occurred:

* aws_vpc.default: Error creating VPC: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: e3cc065c-0573-48fc-a6c6-a7eb760c4680

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by norman-abramovitz** [comment]
btw,  I only set the power user and administrator rights so far.

**Comment by jhunt** [comment]
@norman-abramovitz can you run with this one?

**Comment by norman-abramovitz** [comment]
To keep things simple, we need to use the poweruser role,   The adminuser role allows access to IAM service.  Otherwise, they are the same.   I played around with with eliminating permissions, but  not sure the effort is worth it.   The owner of the account will need to create the users (s3 and ec2) users.
