### ISSUE TITLE
Bosh-Init Fails with "Volume Could Not be Found Error"

### ISSUE THREAD

**Issue by BR0phee** [starkandwayne/codex#91]
I'm using codex/genesis to create a proto-bosh server on AWS.  

Using AMI (BOSH-598bee0f-baf0-4277-a4be-3881d75f63d8 (ami-c31690a3)).  The config creates the bosh AWS instance, creates a 20 GB EBS volume, attaches the volume, then apparently tries to mount the volume and dies - posting the error:

> Action Failed get_task: Task 4345373c-f99a-4d66-70d5-2a6ffac52ddc result: Persistent disk with volume id 'vol-0c6c067fe35711946' could not be found

See attached file for a bit of analysis - it looks like the client side (genesis and bosh-init) think that the device is going to be attached as /dev/sdf, and the server side (AWS) created the volume as /dev/xvdf.  

Any Ideas re: resolution: greatly appreciated.  Thanks in advance!

[Analysis.txt](https://github.com/starkandwayne/codex/files/797880/Analysis.txt)

**Comment by jhunt** [comment]
I believe this was solved with an upgrade of the `bosh-init` binary.
