### ISSUE TITLE
AWS Terraform deploy fail  due to timeout 

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#93]
In attempt to create AWS environment using Terraform I end up with the following error 👍 

>aws_instance.bastion: Still creating... (5m40s elapsed)
>Error applying plan:
>
>1 error(s) occurred:
>
>* dial tcp 10.4.0.156:22: i/o timeout
>
>Terraform does not automatically rollback in the face of errors.
>Instead, your Terraform state file has been partially updated with
>any resources that successfully completed. Please address the error
>above and apply again to incrementally change your infrastructure.
>make: *** [deploy] Error 1

I can see that bastion resource is getting created shortly before the error message appear.

Could you please advice?

**Comment by ipolyzos** [comment]
I just realised that tries to access the internal IP i.e. 10.4... instead of the public one i.e. 

> aws_instance.bastion: Still creating... (3m11s elapsed)
> aws_instance.bastion (remote-exec): Connecting to remote host via SSH...
> aws_instance.bastion (remote-exec):   Host: 10.4.0.150
> aws_instance.bastion (remote-exec):   User: ubuntu
> aws_instance.bastion (remote-exec):   Password: false
> aws_instance.bastion (remote-exec):   Private key: true
> aws_instance.bastion (remote-exec):   SSH Agent: false
> aws_instance.bastion: Still creating... (3m21s elapsed)

**Comment by quintessence** [comment]
Trying to replicate this today. Will get back to you :)

**Comment by quintessence** [comment]
It looks like this was being caused by the Elastic IP being created _after_ the bastion, which was a bit problematic as the bastion create needed to SSH to run the setup script. Sorry about that! There's a quick commit coming up to fix it.
