### ISSUE TITLE
fail to compile ruby_aws_cpi on beta deployment

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#95]
on the first beta environment deployment, i get a failure on compiling **ruby_aws_cpi** i.e.

>  Started compiling packages > ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042. >Failed: Timed out pinging to e19ad7b2-134c-433f-8e80-22a2157bb46d after 600 seconds (00:11:08)
>   Failed compiling packages > registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f: Timed out pinging to bfe0c4f8-1a83-4249-906c-4e13939c766c after 600 seconds (00:11:09)

 bosh task  debug information below :

<pre>
...
D, [2017-03-06 22:32:37 #21114] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting                                                             [47/1913]D, [2017-03-06 22:32:37 #21114] [compile_package(registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.9)] DEBUG -- Di
rectorJobRunner: (0.000131s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [compile_package(registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.9)] DEBUG -- Di
rectorJobRunner: (0.000100s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [compile_package(registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.9)] DEBUG -- Di
rectorJobRunner: (0.000091s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [compile_package(registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.9)] DEBUG -- Di
rectorJobRunner: (0.003131s) DELETE FROM "locks" WHERE (("name" = 'lock:compile:129:1') AND ("uid" = 'dc0722a0-2bbd-40ee-af5f-043cb537a69c'))
D, [2017-03-06 22:32:37 #21114] [compile_package(registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.9)] DEBUG -- Di
rectorJobRunner: Deleted lock: lock:compile:129:1 uid: dc0722a0-2bbd-40ee-af5f-043cb537a69c
E, [2017-03-06 22:32:37 #21114] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Timed out pinging to bfe0c4f8-1a83-4249-906c-4e13939c766c after 6
00 seconds - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:187:in `rescue in wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:193:in `wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:66:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instanc
e'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compi
le_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_packag
e'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 leve
ls) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in proc
ess_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 leve
ls) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-03-06 22:32:37 #21114] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: Waiting for tasks to complete
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2017-03-06 22:32:37 #21114] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.002164s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.000125s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.000125s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.001100s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:us-east-1-staging-bosh')
 AND ("uid" = '6d673107-b68e-4338-9661-fa68b7516caf'))
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.001100s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:us-east-1-staging-bosh') AND ("uid" = '6d673107-b68e-4338-9661-fa68b7516caf'))
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:us-east-1-staging-bosh uid: 6d673107-b68e-4338-9661-fa68b7516caf
I, [2017-03-06 22:32:37 #21114] [task:59]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"d0f8e634-989e-4587-bd33-807c64fcaf22","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'us-east-1-staging-bosh' against Director '2dc0830e-5d3f-4f88-ad10-17ce67bbb79e': #<Bosh::Director::RpcTimeout: Timed out pinging to e19ad7b2-134c-433f-8e80-22a2157bb46d after 600 seconds>","created_at":1488839557}
E, [2017-03-06 22:32:37 #21114] [task:59] ERROR -- DirectorJobRunner: Timed out pinging to e19ad7b2-134c-433f-8e80-22a2157bb46d after 600 seconds
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:187:in `rescue in wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:193:in `wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:66:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.000126s) SELECT NULL
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.000087s) BEGIN
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.000331s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-03-06 22:32:37.065384+0000', "description" = 'create deployment', "result" = 'Timed out pinging to e19ad7b2-134c-433f-8e80-22a2157bb46d after 600 seconds', "output" = '/var/vcap/store/director/tasks/59', "checkpoint_time" = '2017-03-06 22:21:27.802302+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'us-east-1-staging-bosh', "started_at" = '2017-03-06 22:21:27.802235+0000' WHERE ("id" = 59)
D, [2017-03-06 22:32:37 #21114] [task:59] DEBUG -- DirectorJobRunner: (0.001087s) COMMIT
I, [2017-03-06 22:32:37 #21114] []  INFO -- DirectorJobRunner: Task took 11 minutes 9.268047111999977 seconds to process.

Task 59 error
</pre>

could you please advice?

**Comment by geofffranks** [comment]
Seems like the compilation VM isn't able to talk back to the BOSH director that created it. Does it have network access to do so? Maybe a missing security group or bad network setting?

**Comment by ipolyzos** [comment]
the issue raised due to an ACL that prevented communication, thank you for the help
