### ISSUE TITLE
database_z1 fail to deploy

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#96]
in an attempt to deploy cf in following codex documentation I end up in a failure in the _database_z1_ update due to _BBS_, I can not find much for logs though could you please advice?

the error i see is the following : 
> Started updating job database_z1 > database_z1/0 (98c91ba4-f4ec-4c60-82e4-aa9b748e0f66) (canary). Failed: 'database_z1/0 (98c91ba4-f4ec-4c60-82e4-aa9b748e0f66)' is not running after update. Review logs for failed jobs:

(logs attached)
[bbs.stdout.log.txt](https://github.com/starkandwayne/codex/files/831548/bbs.stdout.log.txt)
[bbs.stderr.log.txt](https://github.com/starkandwayne/codex/files/831547/bbs.stderr.log.txt)

 bbs (00:03:18)
>
>Error 400007: 'database_z1/0 (98c91ba4-f4ec-4c60-82e4-aa9b748e0f66)' is not running after update. Review logs for failed jobs: bbs

**Comment by geofffranks** [comment]
@xiujiao Can you get the codex docs updated to have the correct db_connection_strings overridden in properties.yml, since cf-deployments removed the default value?

**Comment by xiujiao** [comment]
@geofffranks Thank you for pointing this out. Please see https://github.com/starkandwayne/codex/pull/97

**Comment by xiujiao** [comment]
@ipolyzos Are you deploying to AWS? If you are deploying to Openstack, except `db_connection_string`, there will be more changes need to be made since the Openstack doc is not consistent with the template yet

**Comment by quintessence** [comment]
@xj - @ipolyzos is deploying to AWS based on previous tickets :) So the update an AWS update would be adequate :)

**Comment by ipolyzos** [comment]
Thnx alot everybody!
